- 👋 Hi, I’m @mekuanint333
- 👀 I’m interested in software devlopment and coding d/f language...
- 🌱 I’m currently devlop our website ...
- 💞️ I’m looking to collaborate on private and govermental org...
- 📫 How to reach me self devlopment every day learn copmputer language seriousliy...

<!---
mekuanint333/mekuanint333 is a ✨ special ✨ repository because its `README.md` (this file) appears on your GitHub profile.
You can click the Preview link to take a look at your changes.
--->
